packageExtensions:
  postcss-tape@*:
    peerDependencies:
      postcss: ^8.0.0
  yaspeller@*:
    dependencies:
      parse-json: ^5.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

# https://github.com/yarnpkg/berry/issues/638
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-2.2.2.cjs
