compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  postcss-tape@*:
    peerDependencies:
      postcss: ^8.0.0
  yaspeller@*:
    dependencies:
      parse-json: ^5.0.0

yarnPath: .yarn/releases/yarn-4.12.0.cjs
